import './globals.css'
import { Inter } from 'next/font/google'

import { Header } from 'src/app/components/Header';
import { Footer } from 'src/app/components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashboard Sandbox',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
